###
POST http://localhost:4000/api/category HTTP/1.1
Content-Type: application/json

{
    "name": "Cuidado del Cabello",
    "description": "El cuidado del cabello es una parte esencial de nuestra rutina diaria de belleza y bienestar. Esta categoría ofrece una amplia gama de productos diseñados para mantener y mejorar la salud, la textura y la apariencia de tu cabello."
}

###
GET http://localhost:4000/api/category HTTP/1.1

###
GET http://localhost:4000/api/category/652b12a95250e8518245169f HTTP/1.1

###
PUT http://localhost:4000/api/category/652b104fbec6806d4d0153cf HTTP/1.1
Content-Type: application/json

{
    "name": "Cuidado de la piel",
    "description": "Estos productos están diseñados para limpiar, hidratar, proteger y tratar diferentes tipos de piel, abordando preocupaciones específicas como la sequedad, el acné, las arrugas, la pigmentación irregular y más."
}

###
DELETE http://localhost:4000/api/category/652b0b994a3217761ba2d06d HTTP/1.1
